### ISSUE TITLE
[Suggestion] Command to solely toggle off flight

### ISSUE THREAD

**Issue by JohnS19** [TownyAdvanced/TownyFlight#13]
A command to solely toggle off flight. To remove flight if given the permission temporarily.

**Comment by LlmDl** [comment]
Would this be run from the console or by the player who's flying?

**Comment by JohnS19** [comment]
console

**Comment by LlmDl** [comment]
I haven't tested this at all but if you wouldn't mind: https://www.dropbox.com/s/oh6e4kcz24bf98r/TownyFlight-1.3.0.jar?dl=0

The command can only be run from the console, just use 'tfly {playername}' 

I'm curious as to what happens when a player is offline and that command is used. Whether it errors out, or whether they lose their flight while logged off and then fall to their deaths. Please try that out for me.

**Comment by JohnS19** [comment]
- the tab complete of the plugin shows "tfly {name}" which is amusing.
- When I use the command from console on someone, it says "Activated" instead of "De-Activated" every time.
- Stacktrace when done on offline player: https://hasteb.in/figixoga.lua
- They do not lose flight, but I am not completely sure since I only used it on someone with bypass.

**Comment by LlmDl** [comment]
Ok, I tested it quite thoroughly and have posted it on spigot: https://www.spigotmc.org/resources/townyflight.50360/update?update=288043
