### ISSUE TITLE
flight preservation - chorus

### ISSUE THREAD

**Issue by Chypik** [TownyAdvanced/TownyFlight#64]
If a player is on the border of a city in flight and begins to eat the fruit of horus, he begins to teleport and about 5-7 times he is accidentally teleported outside the chapels of the city and the flight remains active. Until the moment of entering the city limits or re-entering the game. As I understand it, the plugin does not understand that the player has crossed the border of the city.

latest.log
https://pastebin.com/Bgn2K8mB

TownyFlight/config.yml
https://pastebin.com/3en432xf

**Comment by LlmDl** [comment]
Unable to reproduce this using your config, it is the same as when I tried using your instructions on the discord: flight is always removed when the ChorusFruit teleports me to the wilderness. 

This makes sense because the PlayerTeleportEvent thrown by the Chorus Fruit triggers a PlayerMoveEvent which creates the PlayerChangePlotEvent that TownyFlight uses to decide if flight should be removed.

**Comment by Chypik** [comment]
here's the video :
[https://drive.google.com/file/d/1RStPe30yta8fbWAwY3E85qQ-Wb1mMEpb/view]
